---
title: "Recursos"
---

## Libros Recomendados

### R for Data Science
El libro principal de referencia para este curso:

* [Versión en inglés](https://r4ds.hadley.nz/)
* [Versión en español](https://es.r4ds.hadley.nz/)

## Recursos de Tidyverse

### Documentación Oficial
* [Tidyverse](https://www.tidyverse.org/)
* [dplyr](https://dplyr.tidyverse.org/): Manipulación de datos
* [tidyr](https://tidyr.tidyverse.org/): Organización de datos
* [readr](https://readr.tidyverse.org/): Lectura de datos
* [ggplot2](https://ggplot2.tidyverse.org/): Visualización de datos
* [stringr](https://stringr.tidyverse.org/): Manipulación de cadenas de texto
* [forcats](https://forcats.tidyverse.org/): Manejo de factores
* [lubridate](https://lubridate.tidyverse.org/): Manejo de fechas

### Paquetes Adicionales
* [janitor](https://sfirke.github.io/janitor/): Limpieza de datos
* [here](https://here.r-lib.org/): Rutas de archivos reproducibles
* [sf](https://r-spatial.github.io/sf/): Datos espaciales
* [readxl](https://readxl.tidyverse.org/): Lectura de archivos Excel
* [writexl](https://docs.ropensci.org/writexl/): Escritura de archivos Excel

## Hojas de Referencia (Cheatsheets)

* [RStudio Cheatsheets](https://posit.co/resources/cheatsheets/): Colección completa de hojas de referencia
* [dplyr Cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-transformation.pdf)
* [tidyr Cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf)
* [readr/readxl Cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-import.pdf)

## Comunidades y Recursos de Aprendizaje

* [RStudio Community](https://community.rstudio.com/): Foro de la comunidad
* [Stack Overflow - R](https://stackoverflow.com/questions/tagged/r): Preguntas y respuestas
* [R-bloggers](https://www.r-bloggers.com/): Blog agregador de contenido sobre R

## Recursos en Español

* [R para Ciencia de Datos (libro traducido)](https://es.r4ds.hadley.nz/)
* [Ciencia de Datos con R](https://github.com/cienciadedatos)

## Recursos de Datos Espaciales

### Libros y Tutoriales

* [Geocomputation with R](https://r.geocompx.org/): Libro completo sobre análisis geoespacial con R
* [Spatial Data Science](https://r-spatial.org/book/): Libro sobre ciencia de datos espaciales
* [sf package documentation](https://r-spatial.github.io/sf/): Documentación oficial del paquete sf

### Tutoriales de Michael T. Hallworth

* [Introduction to spatial data analysis using the tidyverse](https://mhallwor.github.io/_pages/Tidyverse_intro): Integración de sf con tidyverse
* [Introduction to spatial points in R](https://mhallwor.github.io/_pages/basics_SpatialPoints): Trabajo con puntos espaciales
* [Introduction to spatial lines in R](https://mhallwor.github.io/_pages/basics_SpatialLines): Trabajo con líneas
* [Introduction to spatial polygons in R](https://mhallwor.github.io/_pages/basics_SpatialPolygons): Trabajo con polígonos
* [Spatial Predicates](https://mhallwor.github.io/_pages/spatial_predicates): Operaciones espaciales
* [Making maps in R](https://mhallwor.github.io/_pages/MakingMaps): Creación de mapas
* [Introduction to raster data in R](https://mhallwor.github.io/_pages/basics_Rasters): Datos ráster
* [Extracting raster data](https://mhallwor.github.io/_pages/activities_ExtractingRasterValues): Extracción de valores ráster
* [Advanced tools for raster data in R](https://mhallwor.github.io/_pages/advanced_Rasters): Herramientas avanzadas para ráster
* [Generating territories](https://mhallwor.github.io/_pages/activities_GenerateTerritories): Generación de territorios

### Paquetes Espaciales Principales

* **sf**: Simple Features para datos vectoriales
* **terra**: Paquete moderno para datos ráster (reemplaza a raster)
* **stars**: Datos espacio-temporales en arrays
* **mapview**: Visualización interactiva de datos espaciales
* **leaflet**: Mapas interactivos web
* **tmap**: Mapas temáticos
* **ggspatial**: Extensión de ggplot2 para mapas

### Hojas de Referencia Espaciales

* [sf Cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/sf.pdf): Referencia rápida del paquete sf
* [Spatial Data in R](https://github.com/rstudio/cheatsheets): Hojas de referencia espaciales

### Sistemas de Coordenadas

* [EPSG.io](https://epsg.io/): Búsqueda de códigos EPSG y sistemas de coordenadas
* [Spatial Reference](https://spatialreference.org/): Referencia de sistemas espaciales
* [Projection Wizard](https://projectionwizard.org/): Asistente para elegir proyecciones
