<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8f6726c79dff2af28c45c64c8336ec2b.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="Paul Efren Santos Andrade // Febrero 2026">
  <title>Introducción a la Programación con R - Tidyverse</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #000000; background-color: #ffffff; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #000000; } /* Normal */
    code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
    code span.an { color: #ca60ca; } /* Annotation */
    code span.at { color: #0057ae; } /* Attribute */
    code span.bn { color: #b08000; } /* BaseN */
    code span.bu { color: #644a9b; } /* BuiltIn */
    code span.cf { color: #000000; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #924c9d; } /* Char */
    code span.cn { color: #aa5500; } /* Constant */
    code span.co { color: #898887; } /* Comment */
    code span.cv { color: #0095ff; } /* CommentVar */
    code span.do { color: #607880; } /* Documentation */
    code span.dt { color: #0057ae; } /* DataType */
    code span.dv { color: #b08000; } /* DecVal */
    code span.er { color: #bf0303; text-decoration: underline; } /* Error */
    code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
    code span.fl { color: #b08000; } /* Float */
    code span.fu { color: #644a9b; } /* Function */
    code span.im { color: #644a9b; } /* Import */
    code span.in { color: #b08000; } /* Information */
    code span.kw { color: #000000; font-weight: bold; } /* Keyword */
    code span.op { color: #000000; } /* Operator */
    code span.ot { color: #006e28; } /* Other */
    code span.pp { color: #006e28; } /* Preprocessor */
    code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
    code span.sc { color: #ff5500; } /* SpecialChar */
    code span.ss { color: #ff5500; } /* SpecialString */
    code span.st { color: #bf0303; } /* String */
    code span.va { color: #0057ae; } /* Variable */
    code span.vs { color: #bf0303; } /* VerbatimString */
    code span.wa { color: #bf0303; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-1689b0f0abb7a24a2a855b68885a866e.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Introducción a la Programación con R - Tidyverse">
<meta property="og:description" content="Sesión 4: Organización de Datos">
<meta name="twitter:title" content="Introducción a la Programación con R - Tidyverse">
<meta name="twitter:description" content="Sesión 4: Organización de Datos">
<meta name="twitter:creator" content="@PaulESantos">
<meta name="twitter:card" content="summary">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introducción a la Programación con R - Tidyverse</h1>
  <p class="subtitle">Sesión 4: Organización de Datos</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<a href="https://paulefrensa.rbind.io" style="color:#28a87d;font-weight:600;">Paul Efren Santos Andrade</a> // Febrero 2026 
</div>
</div>
</div>

</section>
<section id="esquema-de-la-sesión" class="slide level2 smaller">
<h2>Esquema de la sesión</h2>
<ul>
<li class="fragment">¿Qué son datos ordenados (tidy data)?</li>
<li class="fragment">Principios de datos tidy</li>
<li class="fragment">Alargar datos: <code>pivot_longer()</code></li>
<li class="fragment">Ensanchar datos: <code>pivot_wider()</code></li>
<li class="fragment">Casos especiales y problemas comunes</li>
<li class="fragment">Ejercicios prácticos</li>
</ul>
</section>
<section>
<section id="introducción" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Introducción</h1>

</section>
<section id="una-cita-famosa" class="slide level2">
<h2>Una cita famosa</h2>
<blockquote>
<p>“Las familias felices son todas iguales; cada familia infeliz es infeliz a su manera.”</p>
<p>— Leo Tolstoy</p>
</blockquote>
<div class="fragment">
<blockquote>
<p>“Los conjuntos de datos ordenados son todos iguales, pero cada conjunto de datos desordenado es desordenado a su manera.”</p>
<p>— Hadley Wickham</p>
</blockquote>
</div>
</section>
<section id="por-qué-ordenar-datos" class="slide level2">
<h2>¿Por qué ordenar datos?</h2>
<ul>
<li class="fragment">La mayoría de los datos reales están <strong>desordenados</strong></li>
<li class="fragment">Organizar datos toma tiempo al inicio</li>
<li class="fragment">Pero ahorra <strong>mucho más tiempo</strong> después</li>
<li class="fragment">Con datos ordenados, el análisis es más fácil</li>
<li class="fragment">Las herramientas del tidyverse funcionan mejor con datos ordenados</li>
</ul>
</section>
<section id="cargar-paquetes" class="slide level2">
<h2>Cargar paquetes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El paquete <strong>tidyr</strong> (parte de tidyverse) proporciona herramientas para ordenar datos.</p>
</section></section>
<section>
<section id="qué-son-datos-tidy" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>¿Qué son datos tidy?</h1>

</section>
<section id="los-mismos-datos-3-formas-diferentes" class="slide level2 smaller">
<h2>Los mismos datos, 3 formas diferentes</h2>
<p><strong>Tabla 1:</strong></p>
<pre><code>  country      year  cases population
  Afghanistan  1999    745   19987071
  Afghanistan  2000   2666   20595360
  Brazil       1999  37737  172006362</code></pre>
<div class="fragment">
<p><strong>Tabla 2:</strong></p>
<pre><code>  country      year type           count
  Afghanistan  1999 cases            745
  Afghanistan  1999 population  19987071
  Afghanistan  2000 cases           2666</code></pre>
</div>
<div class="fragment">
<div class="question">
<p>¿Cuál es más fácil de usar?</p>
</div>
</div>
</section>
<section id="los-tres-principios-de-datos-tidy" class="slide level2">
<h2>Los tres principios de datos tidy</h2>
<ol type="1">
<li><strong>Cada variable es una columna</strong></li>
<li><strong>Cada observación es una fila</strong></li>
<li><strong>Cada valor es una celda</strong></li>
</ol>
</section>
<section id="visualización-de-los-principios" class="slide level2">
<h2>Visualización de los principios</h2>

<img data-src="https://r4ds.hadley.nz/images/tidy-1.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li class="fragment">Variables → Columnas</li>
<li class="fragment">Observaciones → Filas</li>
<li class="fragment">Valores → Celdas</li>
</ul>
</section>
<section id="por-qué-usar-datos-tidy" class="slide level2">
<h2>¿Por qué usar datos tidy?</h2>
<ol type="1">
<li class="fragment"><strong>Consistencia</strong>: Una forma estándar de almacenar datos
<ul>
<li class="fragment">Fácil aprender herramientas que funcionan con esta estructura</li>
<li class="fragment">Todas tienen uniformidad subyacente</li>
</ul></li>
<li class="fragment"><strong>Naturaleza vectorizada de R</strong>:
<ul>
<li class="fragment">Variables en columnas permiten que R brille</li>
<li class="fragment">Funciones de R trabajan con vectores de valores</li>
<li class="fragment">Transformar datos tidy es natural</li>
</ul></li>
</ol>
</section>
<section id="ejemplo-trabajar-con-datos-tidy" class="slide level2 smaller">
<h2>Ejemplo: Trabajar con datos tidy</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="co"># Calcular tasa por 10,000 habitantes</span></span>
<span id="cb4-2"><a></a>table1 <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a></a>  <span class="fu">mutate</span>(<span class="at">rate =</span> cases <span class="sc">/</span> population <span class="sc">*</span> <span class="dv">10000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  country      year  cases population  rate
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
1 Afghanistan  1999    745   19987071 0.373
2 Afghanistan  2000   2666   20595360 1.29 
3 Brazil       1999  37737  172006362 2.19 
4 Brazil       2000  80488  174504898 4.61 
5 China        1999 212258 1272915272 1.67 
6 China        2000 213766 1280428583 1.67 </code></pre>
</div>
</div>
<pre><code>  country      year  cases population  rate
  Afghanistan  1999    745   19987071  0.373
  Afghanistan  2000   2666   20595360  1.29
  Brazil       1999  37737  172006362  2.19</code></pre>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="co"># Casos totales por año</span></span>
<span id="cb7-2"><a></a>table1 <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a></a>  <span class="fu">summarize</span>(<span class="at">total_cases =</span> <span class="fu">sum</span>(cases))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
   year total_cases
  &lt;dbl&gt;       &lt;dbl&gt;
1  1999      250740
2  2000      296920</code></pre>
</div>
</div>
<pre><code>   year total_cases
   1999      250740
   2000      296920</code></pre>
</div>
</section>
<section id="visualizar-datos-tidy" class="slide level2">
<h2>Visualizar datos tidy</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">ggplot</span>(table1, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> cases)) <span class="sc">+</span></span>
<span id="cb10-2"><a></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> country), <span class="at">color =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> country, <span class="at">shape =</span> country)) <span class="sc">+</span></span>
<span id="cb10-4"><a></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="04-tidying-data_files/figure-revealjs/unnamed-chunk-4-1.png" width="2000" class="r-stretch"><div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Con datos tidy, crear visualizaciones es directo y simple</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="alargar-datos-pivot_longer" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Alargar datos: pivot_longer()</h1>

</section>
<section id="problema-común-datos-en-nombres-de-columnas" class="slide level2">
<h2>Problema común: Datos en nombres de columnas</h2>
<p>La mayoría de datos reales están <strong>desordenados</strong> por dos razones:</p>
<ol type="1">
<li class="fragment">Los datos se organizan para facilitar <strong>entrada</strong>, no análisis</li>
<li class="fragment">La mayoría de personas no conocen principios de datos tidy</li>
</ol>
<div class="fragment">
<p><strong>Solución</strong>: <code>pivot_longer()</code> y <code>pivot_wider()</code></p>
</div>
</section>
<section id="ejemplo-billboard" class="slide level2">
<h2>Ejemplo: Billboard</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>billboard</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 317 × 79
   artist     track date.entered   wk1   wk2   wk3   wk4   wk5   wk6   wk7   wk8
   &lt;chr&gt;      &lt;chr&gt; &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 2 Pac      Baby… 2000-02-26      87    82    72    77    87    94    99    NA
 2 2Ge+her    The … 2000-09-02      91    87    92    NA    NA    NA    NA    NA
 3 3 Doors D… Kryp… 2000-04-08      81    70    68    67    66    57    54    53
 4 3 Doors D… Loser 2000-10-21      76    76    72    69    67    65    55    59
 5 504 Boyz   Wobb… 2000-04-15      57    34    25    17    17    31    36    49
 6 98^0       Give… 2000-08-19      51    39    34    26    26    19     2     2
 7 A*Teens    Danc… 2000-07-08      97    97    96    95   100    NA    NA    NA
 8 Aaliyah    I Do… 2000-01-29      84    62    51    41    38    35    35    38
 9 Aaliyah    Try … 2000-03-18      59    53    38    28    21    18    16    14
10 Adams, Yo… Open… 2000-08-26      76    76    74    69    68    67    61    58
# ℹ 307 more rows
# ℹ 68 more variables: wk9 &lt;dbl&gt;, wk10 &lt;dbl&gt;, wk11 &lt;dbl&gt;, wk12 &lt;dbl&gt;,
#   wk13 &lt;dbl&gt;, wk14 &lt;dbl&gt;, wk15 &lt;dbl&gt;, wk16 &lt;dbl&gt;, wk17 &lt;dbl&gt;, wk18 &lt;dbl&gt;,
#   wk19 &lt;dbl&gt;, wk20 &lt;dbl&gt;, wk21 &lt;dbl&gt;, wk22 &lt;dbl&gt;, wk23 &lt;dbl&gt;, wk24 &lt;dbl&gt;,
#   wk25 &lt;dbl&gt;, wk26 &lt;dbl&gt;, wk27 &lt;dbl&gt;, wk28 &lt;dbl&gt;, wk29 &lt;dbl&gt;, wk30 &lt;dbl&gt;,
#   wk31 &lt;dbl&gt;, wk32 &lt;dbl&gt;, wk33 &lt;dbl&gt;, wk34 &lt;dbl&gt;, wk35 &lt;dbl&gt;, wk36 &lt;dbl&gt;,
#   wk37 &lt;dbl&gt;, wk38 &lt;dbl&gt;, wk39 &lt;dbl&gt;, wk40 &lt;dbl&gt;, wk41 &lt;dbl&gt;, wk42 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<pre><code># A tibble: 317 × 79
  artist       track               date.entered   wk1   wk2   wk3
  &lt;chr&gt;        &lt;chr&gt;               &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 2 Pac        Baby Don't Cry      2000-02-26      87    82    72
2 2Ge+her      The Hardest Part    2000-09-02      91    87    92
3 3 Doors Down Kryptonite          2000-04-08      81    70    68
# ... with 73 more columns: wk4, wk5, wk6, ...</code></pre>
</section>
<section id="problema-con-billboard" class="slide level2">
<h2>Problema con billboard</h2>
<ul>
<li class="fragment">Cada observación es una <strong>canción</strong></li>
<li class="fragment"><code>artist</code>, <code>track</code>, <code>date.entered</code> son variables</li>
<li class="fragment">Pero <code>wk1</code>, <code>wk2</code>, … <code>wk76</code> también son columnas</li>
<li class="fragment">Los <strong>nombres de columnas</strong> son valores de una variable (<code>week</code>)</li>
<li class="fragment">Los <strong>valores de las celdas</strong> son otra variable (<code>rank</code>)</li>
</ul>
</section>
<section id="solución-pivot_longer" class="slide level2">
<h2>Solución: pivot_longer()</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>billboard <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb14-3"><a></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"wk"</span>),</span>
<span id="cb14-4"><a></a>    <span class="at">names_to =</span> <span class="st">"week"</span>,</span>
<span id="cb14-5"><a></a>    <span class="at">values_to =</span> <span class="st">"rank"</span></span>
<span id="cb14-6"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24,092 × 5
   artist track                   date.entered week   rank
   &lt;chr&gt;  &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt; &lt;dbl&gt;
 1 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk1      87
 2 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk2      82
 3 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk3      72
 4 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk4      77
 5 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk5      87
 6 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk6      94
 7 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk7      99
 8 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk8      NA
 9 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk9      NA
10 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk10     NA
# ℹ 24,082 more rows</code></pre>
</div>
</div>
<pre><code># A tibble: 24,092 × 5
   artist track                   date.entered week   rank
   &lt;chr&gt;  &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt; &lt;dbl&gt;
 1 2 Pac  Baby Don't Cry          2000-02-26   wk1      87
 2 2 Pac  Baby Don't Cry          2000-02-26   wk2      82
 3 2 Pac  Baby Don't Cry          2000-02-26   wk3      72</code></pre>
</section>
<section id="argumentos-de-pivot_longer" class="slide level2">
<h2>Argumentos de pivot_longer()</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>billboard <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb17-3"><a></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"wk"</span>),      <span class="co"># Qué columnas pivotar</span></span>
<span id="cb17-4"><a></a>    <span class="at">names_to =</span> <span class="st">"week"</span>,              <span class="co"># Nombre de nueva columna (nombres)</span></span>
<span id="cb17-5"><a></a>    <span class="at">values_to =</span> <span class="st">"rank"</span>              <span class="co"># Nombre de nueva columna (valores)</span></span>
<span id="cb17-6"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24,092 × 5
   artist track                   date.entered week   rank
   &lt;chr&gt;  &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt; &lt;dbl&gt;
 1 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk1      87
 2 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk2      82
 3 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk3      72
 4 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk4      77
 5 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk5      87
 6 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk6      94
 7 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk7      99
 8 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk8      NA
 9 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk9      NA
10 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk10     NA
# ℹ 24,082 more rows</code></pre>
</div>
</div>
<ul>
<li class="fragment"><strong><code>cols</code></strong>: qué columnas pivotar (sintaxis de <code>select()</code>)</li>
<li class="fragment"><strong><code>names_to</code></strong>: nombre para la nueva variable de nombres de columnas</li>
<li class="fragment"><strong><code>values_to</code></strong>: nombre para la nueva variable de valores</li>
</ul>
</section>
<section id="eliminar-valores-faltantes" class="slide level2">
<h2>Eliminar valores faltantes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>billboard <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb19-3"><a></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"wk"</span>),</span>
<span id="cb19-4"><a></a>    <span class="at">names_to =</span> <span class="st">"week"</span>,</span>
<span id="cb19-5"><a></a>    <span class="at">values_to =</span> <span class="st">"rank"</span>,</span>
<span id="cb19-6"><a></a>    <span class="at">values_drop_na =</span> <span class="cn">TRUE</span>  <span class="co"># Eliminar NAs</span></span>
<span id="cb19-7"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,307 × 5
   artist  track                   date.entered week   rank
   &lt;chr&gt;   &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt; &lt;dbl&gt;
 1 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk1      87
 2 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk2      82
 3 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk3      72
 4 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk4      77
 5 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk5      87
 6 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk6      94
 7 2 Pac   Baby Don't Cry (Keep... 2000-02-26   wk7      99
 8 2Ge+her The Hardest Part Of ... 2000-09-02   wk1      91
 9 2Ge+her The Hardest Part Of ... 2000-09-02   wk2      87
10 2Ge+her The Hardest Part Of ... 2000-09-02   wk3      92
# ℹ 5,297 more rows</code></pre>
</div>
</div>
<pre><code># A tibble: 5,307 × 5
  artist track                   date.entered week   rank
  &lt;chr&gt;  &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt; &lt;dbl&gt;
1 2 Pac  Baby Don't Cry          2000-02-26   wk1      87
2 2 Pac  Baby Don't Cry          2000-02-26   wk2      82</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>De 24,092 filas a 5,307 filas - muchos NAs eliminados</p>
</div>
</div>
</div>
</section>
<section id="convertir-tipos-de-datos" class="slide level2">
<h2>Convertir tipos de datos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>billboard_longer <span class="ot">&lt;-</span> billboard <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb22-3"><a></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"wk"</span>),</span>
<span id="cb22-4"><a></a>    <span class="at">names_to =</span> <span class="st">"week"</span>,</span>
<span id="cb22-5"><a></a>    <span class="at">values_to =</span> <span class="st">"rank"</span>,</span>
<span id="cb22-6"><a></a>    <span class="at">values_drop_na =</span> <span class="cn">TRUE</span></span>
<span id="cb22-7"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb22-8"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-9"><a></a>    <span class="at">week =</span> <span class="fu">parse_number</span>(week)  <span class="co"># "wk1" → 1</span></span>
<span id="cb22-10"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><code>parse_number()</code> extrae el primer número de una cadena</p>
</div>
</div>
</div>
</section>
<section id="visualizar-resultados" class="slide level2">
<h2>Visualizar resultados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>billboard_longer <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> week, <span class="at">y =</span> rank, <span class="at">group =</span> track)) <span class="sc">+</span></span>
<span id="cb23-3"><a></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a></a>  <span class="fu">scale_y_reverse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="04-tidying-data_files/figure-revealjs/unnamed-chunk-10-1.png" width="2000" class="r-stretch"><p>Pocas canciones permanecen en el top 100 por más de 20 semanas.</p>
</section>
<section id="cómo-funciona-pivot_longer" class="slide level2 smaller">
<h2>¿Cómo funciona pivot_longer()?</h2>
<p>Ejemplo simple:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>df <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb24-2"><a></a>  <span class="sc">~</span>id,  <span class="sc">~</span>bp1, <span class="sc">~</span>bp2,</span>
<span id="cb24-3"><a></a>   <span class="st">"A"</span>,  <span class="dv">100</span>,  <span class="dv">120</span>,</span>
<span id="cb24-4"><a></a>   <span class="st">"B"</span>,  <span class="dv">140</span>,  <span class="dv">115</span>,</span>
<span id="cb24-5"><a></a>   <span class="st">"C"</span>,  <span class="dv">120</span>,  <span class="dv">125</span></span>
<span id="cb24-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>df <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb25-3"><a></a>    <span class="at">cols =</span> bp1<span class="sc">:</span>bp2,</span>
<span id="cb25-4"><a></a>    <span class="at">names_to =</span> <span class="st">"measurement"</span>,</span>
<span id="cb25-5"><a></a>    <span class="at">values_to =</span> <span class="st">"value"</span></span>
<span id="cb25-6"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  id    measurement value
  &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;
1 A     bp1           100
2 A     bp2           120
3 B     bp1           140
4 B     bp2           115
5 C     bp1           120
6 C     bp2           125</code></pre>
</div>
</div>
<pre><code>  id    measurement value
  A     bp1           100
  A     bp2           120
  B     bp1           140</code></pre>
</div>
</section>
<section id="mecánica-de-pivot_longer" class="slide level2">
<h2>Mecánica de pivot_longer()</h2>

<img data-src="https://r4ds.hadley.nz/images/tidy-pivot-longer.png" class="quarto-figure quarto-figure-center r-stretch"><ol type="1">
<li class="fragment"><strong>Columnas existentes</strong> se repiten (una vez por columna pivotada)</li>
<li class="fragment"><strong>Nombres de columnas</strong> se convierten en valores</li>
<li class="fragment"><strong>Valores de celdas</strong> se desenrollan fila por fila</li>
</ol>
</section>
<section id="múltiples-variables-en-nombres-de-columnas" class="slide level2">
<h2>Múltiples variables en nombres de columnas</h2>
<p>Ejemplo: datos de tuberculosis (WHO)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>who2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,240 × 58
   country      year sp_m_014 sp_m_1524 sp_m_2534 sp_m_3544 sp_m_4554 sp_m_5564
   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 Afghanistan  1980       NA        NA        NA        NA        NA        NA
 2 Afghanistan  1981       NA        NA        NA        NA        NA        NA
 3 Afghanistan  1982       NA        NA        NA        NA        NA        NA
 4 Afghanistan  1983       NA        NA        NA        NA        NA        NA
 5 Afghanistan  1984       NA        NA        NA        NA        NA        NA
 6 Afghanistan  1985       NA        NA        NA        NA        NA        NA
 7 Afghanistan  1986       NA        NA        NA        NA        NA        NA
 8 Afghanistan  1987       NA        NA        NA        NA        NA        NA
 9 Afghanistan  1988       NA        NA        NA        NA        NA        NA
10 Afghanistan  1989       NA        NA        NA        NA        NA        NA
# ℹ 7,230 more rows
# ℹ 50 more variables: sp_m_65 &lt;dbl&gt;, sp_f_014 &lt;dbl&gt;, sp_f_1524 &lt;dbl&gt;,
#   sp_f_2534 &lt;dbl&gt;, sp_f_3544 &lt;dbl&gt;, sp_f_4554 &lt;dbl&gt;, sp_f_5564 &lt;dbl&gt;,
#   sp_f_65 &lt;dbl&gt;, sn_m_014 &lt;dbl&gt;, sn_m_1524 &lt;dbl&gt;, sn_m_2534 &lt;dbl&gt;,
#   sn_m_3544 &lt;dbl&gt;, sn_m_4554 &lt;dbl&gt;, sn_m_5564 &lt;dbl&gt;, sn_m_65 &lt;dbl&gt;,
#   sn_f_014 &lt;dbl&gt;, sn_f_1524 &lt;dbl&gt;, sn_f_2534 &lt;dbl&gt;, sn_f_3544 &lt;dbl&gt;,
#   sn_f_4554 &lt;dbl&gt;, sn_f_5564 &lt;dbl&gt;, sn_f_65 &lt;dbl&gt;, ep_m_014 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<pre><code># A tibble: 7,240 × 58
  country      year sp_m_014 sp_m_1524 sp_m_2534 ep_f_014
  &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 Afghanistan  1980       NA        NA        NA       NA
2 Afghanistan  1981       NA        NA        NA       NA</code></pre>
<p>Nombres de columnas: <code>sp_m_014</code>, <code>ep_f_4554</code>, <code>rel_m_3544</code></p>
</section>
<section id="anatomía-de-los-nombres" class="slide level2">
<h2>Anatomía de los nombres</h2>
<p>Patrón: <code>diagnosis_gender_age</code></p>
<ul>
<li class="fragment"><strong>Primera parte</strong> (<code>sp</code>/<code>rel</code>/<code>ep</code>): método de diagnóstico</li>
<li class="fragment"><strong>Segunda parte</strong> (<code>m</code>/<code>f</code>): género</li>
<li class="fragment"><strong>Tercera parte</strong> (<code>014</code>/<code>1524</code>/etc.): rango de edad</li>
</ul>
</section>
<section id="solución-names_sep" class="slide level2">
<h2>Solución: names_sep</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>who2 <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb31-3"><a></a>    <span class="at">cols =</span> <span class="sc">!</span>(country<span class="sc">:</span>year),</span>
<span id="cb31-4"><a></a>    <span class="at">names_to =</span> <span class="fu">c</span>(<span class="st">"diagnosis"</span>, <span class="st">"gender"</span>, <span class="st">"age"</span>),</span>
<span id="cb31-5"><a></a>    <span class="at">names_sep =</span> <span class="st">"_"</span>,</span>
<span id="cb31-6"><a></a>    <span class="at">values_to =</span> <span class="st">"count"</span></span>
<span id="cb31-7"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 405,440 × 6
   country      year diagnosis gender age   count
   &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt;
 1 Afghanistan  1980 sp        m      014      NA
 2 Afghanistan  1980 sp        m      1524     NA
 3 Afghanistan  1980 sp        m      2534     NA
 4 Afghanistan  1980 sp        m      3544     NA
 5 Afghanistan  1980 sp        m      4554     NA
 6 Afghanistan  1980 sp        m      5564     NA
 7 Afghanistan  1980 sp        m      65       NA
 8 Afghanistan  1980 sp        f      014      NA
 9 Afghanistan  1980 sp        f      1524     NA
10 Afghanistan  1980 sp        f      2534     NA
# ℹ 405,430 more rows</code></pre>
</div>
</div>
<pre><code>  country      year diagnosis gender age   count
  Afghanistan  1980 sp        m      014      NA
  Afghanistan  1980 sp        m      1524     NA
  Afghanistan  1980 sp        f      014      NA</code></pre>
</section>
<section id="datos-y-variables-en-nombres" class="slide level2 smaller">
<h2>Datos y variables en nombres</h2>
<p>Ejemplo: datos de hogares</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>household</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  family dob_child1 dob_child2 name_child1 name_child2
   &lt;int&gt; &lt;date&gt;     &lt;date&gt;     &lt;chr&gt;       &lt;chr&gt;      
1      1 1998-11-26 2000-01-29 Susan       Jose       
2      2 1996-06-22 NA         Mark        &lt;NA&gt;       
3      3 2002-07-11 2004-04-05 Sam         Seth       
4      4 2004-10-10 2009-08-27 Craig       Khai       
5      5 2000-12-05 2005-02-28 Parker      Gracie     </code></pre>
</div>
</div>
<pre><code>  family dob_child1 dob_child2 name_child1 name_child2
       1 1998-11-26 2000-01-29 Susan       Jose
       2 1996-06-22 NA         Mark        &lt;NA&gt;</code></pre>
<ul>
<li class="fragment">Nombres contienen <strong>nombres de variables</strong> (<code>dob</code>, <code>name</code>)</li>
<li class="fragment">Y <strong>valores de otra variable</strong> (<code>child</code>: 1 o 2)</li>
</ul>
</section>
<section id="solución-.value-especial" class="slide level2">
<h2>Solución: .value especial</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>household <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb37-3"><a></a>    <span class="at">cols =</span> <span class="sc">!</span>family,</span>
<span id="cb37-4"><a></a>    <span class="at">names_to =</span> <span class="fu">c</span>(<span class="st">".value"</span>, <span class="st">"child"</span>),</span>
<span id="cb37-5"><a></a>    <span class="at">names_sep =</span> <span class="st">"_"</span>,</span>
<span id="cb37-6"><a></a>    <span class="at">values_drop_na =</span> <span class="cn">TRUE</span></span>
<span id="cb37-7"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  family child  dob        name  
   &lt;int&gt; &lt;chr&gt;  &lt;date&gt;     &lt;chr&gt; 
1      1 child1 1998-11-26 Susan 
2      1 child2 2000-01-29 Jose  
3      2 child1 1996-06-22 Mark  
4      3 child1 2002-07-11 Sam   
5      3 child2 2004-04-05 Seth  
6      4 child1 2004-10-10 Craig 
7      4 child2 2009-08-27 Khai  
8      5 child1 2000-12-05 Parker
9      5 child2 2005-02-28 Gracie</code></pre>
</div>
</div>
<pre><code>  family child  dob        name
       1 child1 1998-11-26 Susan
       1 child2 2000-01-29 Jose
       2 child1 1996-06-22 Mark</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><code>.value</code> indica que la primera parte del nombre se convierte en nombre de columna</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="ensanchar-datos-pivot_wider" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Ensanchar datos: pivot_wider()</h1>

</section>
<section id="cuando-necesitas-pivot_wider" class="slide level2">
<h2>Cuando necesitas pivot_wider()</h2>
<ul>
<li class="fragment">Opuesto a <code>pivot_longer()</code></li>
<li class="fragment"><strong>Aumenta columnas</strong>, <strong>reduce filas</strong></li>
<li class="fragment">Útil cuando una observación está dispersa en múltiples filas</li>
<li class="fragment">Menos común en la práctica</li>
<li class="fragment">Frecuente en datos gubernamentales</li>
</ul>
</section>
<section id="ejemplo-experiencia-de-pacientes" class="slide level2">
<h2>Ejemplo: Experiencia de pacientes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>cms_patient_experience</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 500 × 5
   org_pac_id org_nm                           measure_cd measure_title prf_rate
   &lt;chr&gt;      &lt;chr&gt;                            &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;
 1 0446157747 USC CARE MEDICAL GROUP INC       CAHPS_GRP… CAHPS for MI…       63
 2 0446157747 USC CARE MEDICAL GROUP INC       CAHPS_GRP… CAHPS for MI…       87
 3 0446157747 USC CARE MEDICAL GROUP INC       CAHPS_GRP… CAHPS for MI…       86
 4 0446157747 USC CARE MEDICAL GROUP INC       CAHPS_GRP… CAHPS for MI…       57
 5 0446157747 USC CARE MEDICAL GROUP INC       CAHPS_GRP… CAHPS for MI…       85
 6 0446157747 USC CARE MEDICAL GROUP INC       CAHPS_GRP… CAHPS for MI…       24
 7 0446162697 ASSOCIATION OF UNIVERSITY PHYSI… CAHPS_GRP… CAHPS for MI…       59
 8 0446162697 ASSOCIATION OF UNIVERSITY PHYSI… CAHPS_GRP… CAHPS for MI…       85
 9 0446162697 ASSOCIATION OF UNIVERSITY PHYSI… CAHPS_GRP… CAHPS for MI…       83
10 0446162697 ASSOCIATION OF UNIVERSITY PHYSI… CAHPS_GRP… CAHPS for MI…       63
# ℹ 490 more rows</code></pre>
</div>
</div>
<pre><code>  org_pac_id org_nm                     measure_cd   prf_rate
  0446157747 USC CARE MEDICAL GROUP INC CAHPS_GRP_1        63
  0446157747 USC CARE MEDICAL GROUP INC CAHPS_GRP_2        87
  0446157747 USC CARE MEDICAL GROUP INC CAHPS_GRP_3        86
  0446157747 USC CARE MEDICAL GROUP INC CAHPS_GRP_5        57</code></pre>
</section>
<section id="problema" class="slide level2">
<h2>Problema</h2>
<ul>
<li class="fragment">Cada <strong>organización</strong> es la unidad de observación</li>
<li class="fragment">Pero cada organización está en <strong>6 filas</strong></li>
<li class="fragment">Una fila por cada medida del cuestionario</li>
<li class="fragment">Queremos: <strong>1 fila por organización</strong>, <strong>1 columna por medida</strong></li>
</ul>
</section>
<section id="ver-medidas-únicas" class="slide level2">
<h2>Ver medidas únicas</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>cms_patient_experience <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a></a>  <span class="fu">distinct</span>(measure_cd, measure_title)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  measure_cd   measure_title                                                    
  &lt;chr&gt;        &lt;chr&gt;                                                            
1 CAHPS_GRP_1  CAHPS for MIPS SSM: Getting Timely Care, Appointments, and Infor…
2 CAHPS_GRP_2  CAHPS for MIPS SSM: How Well Providers Communicate               
3 CAHPS_GRP_3  CAHPS for MIPS SSM: Patient's Rating of Provider                 
4 CAHPS_GRP_5  CAHPS for MIPS SSM: Health Promotion and Education               
5 CAHPS_GRP_8  CAHPS for MIPS SSM: Courteous and Helpful Office Staff           
6 CAHPS_GRP_12 CAHPS for MIPS SSM: Stewardship of Patient Resources             </code></pre>
</div>
</div>
<pre><code>  measure_cd   measure_title
  CAHPS_GRP_1  Getting Timely Care, Appointments...
  CAHPS_GRP_2  How Well Providers Communicate
  CAHPS_GRP_3  Patient's Rating of Provider
  CAHPS_GRP_5  Health Promotion and Education
  CAHPS_GRP_8  Courteous and Helpful Office Staff
  CAHPS_GRP_12 Stewardship of Patient Resources</code></pre>
</section>
<section id="solución-pivot_wider" class="slide level2">
<h2>Solución: pivot_wider()</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a>cms_patient_experience <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb46-3"><a></a>    <span class="at">names_from =</span> measure_cd,</span>
<span id="cb46-4"><a></a>    <span class="at">values_from =</span> prf_rate</span>
<span id="cb46-5"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 500 × 9
   org_pac_id org_nm           measure_title CAHPS_GRP_1 CAHPS_GRP_2 CAHPS_GRP_3
   &lt;chr&gt;      &lt;chr&gt;            &lt;chr&gt;               &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
 1 0446157747 USC CARE MEDICA… CAHPS for MI…          63          NA          NA
 2 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          87          NA
 3 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          86
 4 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          NA
 5 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          NA
 6 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          NA
 7 0446162697 ASSOCIATION OF … CAHPS for MI…          59          NA          NA
 8 0446162697 ASSOCIATION OF … CAHPS for MI…          NA          85          NA
 9 0446162697 ASSOCIATION OF … CAHPS for MI…          NA          NA          83
10 0446162697 ASSOCIATION OF … CAHPS for MI…          NA          NA          NA
# ℹ 490 more rows
# ℹ 3 more variables: CAHPS_GRP_5 &lt;dbl&gt;, CAHPS_GRP_8 &lt;dbl&gt;, CAHPS_GRP_12 &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li class="fragment"><code>names_from</code>: columna existente que contiene los <strong>nombres</strong></li>
<li class="fragment"><code>values_from</code>: columna existente que contiene los <strong>valores</strong></li>
</ul>
</section>
<section id="resultado-parcial" class="slide level2">
<h2>Resultado (parcial)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a>cms_patient_experience <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb48-3"><a></a>    <span class="at">names_from =</span> measure_cd,</span>
<span id="cb48-4"><a></a>    <span class="at">values_from =</span> prf_rate</span>
<span id="cb48-5"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 500 × 9
   org_pac_id org_nm           measure_title CAHPS_GRP_1 CAHPS_GRP_2 CAHPS_GRP_3
   &lt;chr&gt;      &lt;chr&gt;            &lt;chr&gt;               &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
 1 0446157747 USC CARE MEDICA… CAHPS for MI…          63          NA          NA
 2 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          87          NA
 3 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          86
 4 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          NA
 5 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          NA
 6 0446157747 USC CARE MEDICA… CAHPS for MI…          NA          NA          NA
 7 0446162697 ASSOCIATION OF … CAHPS for MI…          59          NA          NA
 8 0446162697 ASSOCIATION OF … CAHPS for MI…          NA          85          NA
 9 0446162697 ASSOCIATION OF … CAHPS for MI…          NA          NA          83
10 0446162697 ASSOCIATION OF … CAHPS for MI…          NA          NA          NA
# ℹ 490 more rows
# ℹ 3 more variables: CAHPS_GRP_5 &lt;dbl&gt;, CAHPS_GRP_8 &lt;dbl&gt;, CAHPS_GRP_12 &lt;dbl&gt;</code></pre>
</div>
</div>
<pre><code>  org_pac_id org_nm                   measure_title   CAHPS_GRP_1
  0446157747 USC CARE MEDICAL GROUP   ...                      63
  0446157747 USC CARE MEDICAL GROUP   ...                      NA
  0446157747 USC CARE MEDICAL GROUP   ...                      NA</code></pre>
<div class="question">
<p>¿Por qué todavía hay múltiples filas?</p>
</div>
</section>
<section id="especificar-id_cols" class="slide level2">
<h2>Especificar id_cols</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a>cms_patient_experience <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb51-3"><a></a>    <span class="at">id_cols =</span> <span class="fu">starts_with</span>(<span class="st">"org"</span>),</span>
<span id="cb51-4"><a></a>    <span class="at">names_from =</span> measure_cd,</span>
<span id="cb51-5"><a></a>    <span class="at">values_from =</span> prf_rate</span>
<span id="cb51-6"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 95 × 8
   org_pac_id org_nm CAHPS_GRP_1 CAHPS_GRP_2 CAHPS_GRP_3 CAHPS_GRP_5 CAHPS_GRP_8
   &lt;chr&gt;      &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
 1 0446157747 USC C…          63          87          86          57          85
 2 0446162697 ASSOC…          59          85          83          63          88
 3 0547164295 BEAVE…          49          NA          75          44          73
 4 0749333730 CAPE …          67          84          85          65          82
 5 0840104360 ALLIA…          66          87          87          64          87
 6 0840109864 REX H…          73          87          84          67          91
 7 0840513552 SCL H…          58          83          76          58          78
 8 0941545784 GRITM…          46          86          81          54          NA
 9 1052612785 COMMU…          65          84          80          58          87
10 1254237779 OUR L…          61          NA          NA          65          NA
# ℹ 85 more rows
# ℹ 1 more variable: CAHPS_GRP_12 &lt;dbl&gt;</code></pre>
</div>
</div>
<pre><code>  org_pac_id org_nm           CAHPS_GRP_1 CAHPS_GRP_2 CAHPS_GRP_3
  0446157747 USC CARE MED...           63          87          86
  0446162697 ASSOCIATION ...           59          85          83
  0547164295 BEAVER MED  ...           49          NA          75</code></pre>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><code>id_cols</code> especifica qué columnas identifican únicamente cada fila</p>
</div>
</div>
</div>
</section>
<section id="cómo-funciona-pivot_wider" class="slide level2">
<h2>¿Cómo funciona pivot_wider()?</h2>
<p>Ejemplo simple:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a></a>df <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb54-2"><a></a>  <span class="sc">~</span>id, <span class="sc">~</span>measurement, <span class="sc">~</span>value,</span>
<span id="cb54-3"><a></a>  <span class="st">"A"</span>,        <span class="st">"bp1"</span>,    <span class="dv">100</span>,</span>
<span id="cb54-4"><a></a>  <span class="st">"B"</span>,        <span class="st">"bp1"</span>,    <span class="dv">140</span>,</span>
<span id="cb54-5"><a></a>  <span class="st">"B"</span>,        <span class="st">"bp2"</span>,    <span class="dv">115</span>,</span>
<span id="cb54-6"><a></a>  <span class="st">"A"</span>,        <span class="st">"bp2"</span>,    <span class="dv">120</span>,</span>
<span id="cb54-7"><a></a>  <span class="st">"A"</span>,        <span class="st">"bp3"</span>,    <span class="dv">105</span></span>
<span id="cb54-8"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="aplicar-pivot_wider" class="slide level2">
<h2>Aplicar pivot_wider()</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a>df <span class="sc">|&gt;</span></span>
<span id="cb55-2"><a></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb55-3"><a></a>    <span class="at">names_from =</span> measurement,</span>
<span id="cb55-4"><a></a>    <span class="at">values_from =</span> value</span>
<span id="cb55-5"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  id      bp1   bp2   bp3
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 A       100   120   105
2 B       140   115    NA</code></pre>
</div>
</div>
<pre><code>  id      bp1   bp2   bp3
  A       100   120   105
  B       140   115    NA</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>NAs se crean cuando no hay valor correspondiente en la entrada</p>
</div>
</div>
</div>
</section>
<section id="mecánica-de-pivot_wider" class="slide level2">
<h2>Mecánica de pivot_wider()</h2>
<p><code>pivot_wider()</code> sigue estos pasos:</p>
<ol type="1">
<li class="fragment">Identifica qué irá en <strong>columnas</strong> (valores únicos de <code>names_from</code>)</li>
<li class="fragment">Identifica qué irá en <strong>filas</strong> (variables no usadas = <code>id_cols</code>)</li>
<li class="fragment">Crea data frame vacío combinando filas × columnas</li>
<li class="fragment">Rellena celdas con valores de <code>values_from</code></li>
</ol>
</section>
<section id="valores-duplicados" class="slide level2">
<h2>Valores duplicados</h2>
<p>¿Qué pasa si hay múltiples filas para la misma combinación?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a></a>df <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb58-2"><a></a>  <span class="sc">~</span>id, <span class="sc">~</span>measurement, <span class="sc">~</span>value,</span>
<span id="cb58-3"><a></a>  <span class="st">"A"</span>,        <span class="st">"bp1"</span>,    <span class="dv">100</span>,</span>
<span id="cb58-4"><a></a>  <span class="st">"A"</span>,        <span class="st">"bp1"</span>,    <span class="dv">102</span>,  <span class="co"># Duplicado!</span></span>
<span id="cb58-5"><a></a>  <span class="st">"A"</span>,        <span class="st">"bp2"</span>,    <span class="dv">120</span>,</span>
<span id="cb58-6"><a></a>  <span class="st">"B"</span>,        <span class="st">"bp1"</span>,    <span class="dv">140</span>,</span>
<span id="cb58-7"><a></a>  <span class="st">"B"</span>,        <span class="st">"bp2"</span>,    <span class="dv">115</span></span>
<span id="cb58-8"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="resultado-con-duplicados" class="slide level2 smaller">
<h2>Resultado con duplicados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a></a>df <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb59-3"><a></a>    <span class="at">names_from =</span> measurement,</span>
<span id="cb59-4"><a></a>    <span class="at">values_from =</span> value</span>
<span id="cb59-5"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  id    bp1       bp2      
  &lt;chr&gt; &lt;list&gt;    &lt;list&gt;   
1 A     &lt;dbl [2]&gt; &lt;dbl [1]&gt;
2 B     &lt;dbl [1]&gt; &lt;dbl [1]&gt;</code></pre>
</div>
</div>
<pre><code>Warning: Values from `value` are not uniquely identified;
output will contain list-cols.

  id    bp1       bp2
  A     &lt;dbl [2]&gt; &lt;dbl [1]&gt;
  B     &lt;dbl [1]&gt; &lt;dbl [1]&gt;</code></pre>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Crea list-columns! Necesitas resolver duplicados primero</p>
</div>
</div>
</div>
</section>
<section id="encontrar-duplicados" class="slide level2">
<h2>Encontrar duplicados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a></a>df <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a></a>  <span class="fu">group_by</span>(id, measurement) <span class="sc">|&gt;</span></span>
<span id="cb62-3"><a></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb62-4"><a></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  id    measurement     n
  &lt;chr&gt; &lt;chr&gt;       &lt;int&gt;
1 A     bp1             2</code></pre>
</div>
</div>
<pre><code>  id    measurement     n
  A     bp1             2</code></pre>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Investiga y resuelve el problema antes de pivotar</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="ejemplo-práctico-áreas-naturales" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Ejemplo Práctico: Áreas Naturales</h1>

</section>
<section id="datos-de-ejemplo" class="slide level2">
<h2>Datos de ejemplo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a></a><span class="fu">library</span>(readxl)</span>
<span id="cb65-2"><a></a></span>
<span id="cb65-3"><a></a>anp <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/areas_naturales_peru.xlsx"</span>) <span class="sc">|&gt;</span></span>
<span id="cb65-4"><a></a>  <span class="fu">clean_names</span>()</span>
<span id="cb65-5"><a></a></span>
<span id="cb65-6"><a></a><span class="fu">glimpse</span>(anp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 9
$ x1           &lt;chr&gt; "CATEGORIAS", "PARQUES NACIONALES         (15)", "PARQUES…
$ x2           &lt;chr&gt; "CÓDIGO", "PN 01", "PN 02", "PN 03", "PN 04", "PN 05", "P…
$ x3           &lt;chr&gt; "CATEGORIAS", "de Cutervo", "de Tingo María", "del Manu",…
$ creacion     &lt;chr&gt; "BASE LEGAL", "LEY Nº 13694", "LEY Nº 15574", "D.S. Nº 64…
$ x5           &lt;chr&gt; "FECHA PROMULGACIÓN", "08.09.1961", "14.05.1965", "29.05.…
$ modificacion &lt;chr&gt; "BASE LEGAL", "LEY Nº 28860", NA, "D.S. Nº 045-2002-AG", …
$ x7           &lt;chr&gt; "FECHA PROMULGACIÓN", "03.08.2006", NA, "11.07.2002", NA,…
$ x8           &lt;chr&gt; "UBICACIÓN POLITICA", "CAJAMARCA", "HUANUCO", "CUSCO y MA…
$ x9           &lt;chr&gt; "EXTENSION  (ha)", "8214.23", "4777", "1716295.22", "3400…</code></pre>
</div>
</div>
</section>
<section id="alargar-múltiples-columnas-de-superficie" class="slide level2">
<h2>Alargar: Múltiples columnas de superficie</h2>
<p>Supongamos que tenemos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a></a>anp_wide <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb67-2"><a></a>  <span class="sc">~</span>nombre,              <span class="sc">~</span>superficie_2020, <span class="sc">~</span>superficie_2021,</span>
<span id="cb67-3"><a></a>  <span class="st">"Parque Cutervo"</span>,     <span class="dv">8214</span>,             <span class="dv">8214</span>,</span>
<span id="cb67-4"><a></a>  <span class="st">"Reserva Pacaya"</span>,     <span class="dv">2080000</span>,          <span class="dv">2080000</span>,</span>
<span id="cb67-5"><a></a>  <span class="st">"Parque Manu"</span>,        <span class="dv">1716295</span>,          <span class="dv">1716295</span></span>
<span id="cb67-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="solución" class="slide level2">
<h2>Solución</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a></a>anp_long <span class="ot">&lt;-</span> anp_wide <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb68-3"><a></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"superficie"</span>),</span>
<span id="cb68-4"><a></a>    <span class="at">names_to =</span> <span class="st">"year"</span>,</span>
<span id="cb68-5"><a></a>    <span class="at">names_prefix =</span> <span class="st">"superficie_"</span>,</span>
<span id="cb68-6"><a></a>    <span class="at">values_to =</span> <span class="st">"superficie_ha"</span></span>
<span id="cb68-7"><a></a>  )</span>
<span id="cb68-8"><a></a></span>
<span id="cb68-9"><a></a>anp_long</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  nombre         year  superficie_ha
  &lt;chr&gt;          &lt;chr&gt;         &lt;dbl&gt;
1 Parque Cutervo 2020           8214
2 Parque Cutervo 2021           8214
3 Reserva Pacaya 2020        2080000
4 Reserva Pacaya 2021        2080000
5 Parque Manu    2020        1716295
6 Parque Manu    2021        1716295</code></pre>
</div>
</div>
<pre><code>  nombre              year  superficie_ha
  Parque Cutervo      2020           8214
  Parque Cutervo      2021           8214
  Reserva Pacaya      2020        2080000</code></pre>
</section>
<section id="ensanchar-de-largo-a-ancho" class="slide level2">
<h2>Ensanchar: De largo a ancho</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a></a>anp_long <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb71-3"><a></a>    <span class="at">names_from =</span> year,</span>
<span id="cb71-4"><a></a>    <span class="at">names_prefix =</span> <span class="st">"superficie_"</span>,</span>
<span id="cb71-5"><a></a>    <span class="at">values_from =</span> superficie_ha</span>
<span id="cb71-6"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  nombre         superficie_2020 superficie_2021
  &lt;chr&gt;                    &lt;dbl&gt;           &lt;dbl&gt;
1 Parque Cutervo            8214            8214
2 Reserva Pacaya         2080000         2080000
3 Parque Manu            1716295         1716295</code></pre>
</div>
</div>
<pre><code>  nombre              superficie_2020  superficie_2021
  Parque Cutervo                 8214             8214
  Reserva Pacaya              2080000          2080000
  Parque Manu                 1716295          1716295</code></pre>
</section></section>
<section>
<section id="ejercicios-prácticos" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Ejercicios Prácticos</h1>

</section>
<section id="ejercicio-1-billboard-básico" class="slide level2 smaller">
<h2>Ejercicio 1: Billboard básico</h2>
<div class="task">
<ol type="1">
<li>Toma el dataset <code>billboard</code></li>
<li>Usa <code>pivot_longer()</code> para crear columnas <code>week</code> y <code>rank</code></li>
<li>Elimina valores faltantes</li>
<li>Convierte <code>week</code> a numérico</li>
<li>Filtra solo canciones que llegaron al top 10</li>
<li>Cuenta cuántas semanas cada canción estuvo en top 10</li>
</ol>
</div>
</section>
<section id="ejercicio-2-áreas-naturales" class="slide level2">
<h2>Ejercicio 2: Áreas Naturales</h2>
<div class="task">
<p>Tienes datos con múltiples años de superficie:</p>
<ol type="1">
<li>Crea un tibble con columnas: <code>nombre</code>, <code>superficie_2019</code>, <code>superficie_2020</code>, <code>superficie_2021</code></li>
<li>Usa <code>pivot_longer()</code> para alargar</li>
<li>Convierte el año a numérico</li>
<li>Calcula el cambio de superficie entre años</li>
</ol>
</div>
</section>
<section id="ejercicio-3-who-tuberculosis" class="slide level2">
<h2>Ejercicio 3: WHO tuberculosis</h2>
<div class="task">
<p>Con el dataset <code>who2</code>:</p>
<ol type="1">
<li>Usa <code>pivot_longer()</code> con <code>names_sep</code></li>
<li>Separa <code>diagnosis</code>, <code>gender</code>, y <code>age</code></li>
<li>Calcula casos totales por país y género</li>
<li>Usa <code>pivot_wider()</code> para crear columnas por género</li>
</ol>
</div>
</section>
<section id="ejercicio-4-datos-de-censo" class="slide level2 smaller">
<h2>Ejercicio 4: Datos de censo</h2>
<div class="task">
<p>Crea datos simulados de población por departamento:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a></a>censo <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb74-2"><a></a>  <span class="sc">~</span>departamento, <span class="sc">~</span>poblacion_urbana, <span class="sc">~</span>poblacion_rural,</span>
<span id="cb74-3"><a></a>  <span class="st">"Lima"</span>,        <span class="dv">9000000</span>,           <span class="dv">500000</span>,</span>
<span id="cb74-4"><a></a>  <span class="st">"Cusco"</span>,       <span class="dv">400000</span>,            <span class="dv">800000</span>,</span>
<span id="cb74-5"><a></a>  <span class="st">"Loreto"</span>,      <span class="dv">300000</span>,            <span class="dv">700000</span></span>
<span id="cb74-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>Alarga los datos</li>
<li>Calcula población total por departamento</li>
<li>Calcula porcentaje urbano/rural</li>
<li>Ensancha para comparar departamentos</li>
</ol>
</div>
</section></section>
<section>
<section id="resumen" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>Resumen</h1>

</section>
<section id="conceptos-clave" class="slide level2">
<h2>Conceptos clave</h2>
<ul>
<li class="fragment"><strong>Datos tidy</strong>: variables en columnas, observaciones en filas, valores en celdas</li>
<li class="fragment"><strong>pivot_longer()</strong>: convertir columnas en filas (alargar)</li>
<li class="fragment"><strong>pivot_wider()</strong>: convertir filas en columnas (ensanchar)</li>
<li class="fragment">No hay “una” forma correcta - depende del análisis</li>
<li class="fragment">Está bien des-ordenar, transformar, y re-ordenar según necesites</li>
</ul>
</section>
<section id="funciones-principales" class="slide level2">
<h2>Funciones principales</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Función</th>
<th>Uso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>pivot_longer()</code></td>
<td>Alargar datos (columnas → filas)</td>
</tr>
<tr class="even">
<td><code>pivot_wider()</code></td>
<td>Ensanchar datos (filas → columnas)</td>
</tr>
<tr class="odd">
<td><code>names_to</code></td>
<td>Nombre para nueva columna de nombres</td>
</tr>
<tr class="even">
<td><code>values_to</code></td>
<td>Nombre para nueva columna de valores</td>
</tr>
<tr class="odd">
<td><code>names_from</code></td>
<td>De dónde tomar nombres de columnas</td>
</tr>
<tr class="even">
<td><code>values_from</code></td>
<td>De dónde tomar valores</td>
</tr>
<tr class="odd">
<td><code>names_sep</code></td>
<td>Separador para dividir nombres</td>
</tr>
<tr class="even">
<td><code>.value</code></td>
<td>Indicador especial para nombres variables</td>
</tr>
</tbody>
</table>
</section>
<section id="argumentos-importantes" class="slide level2 smaller">
<h2>Argumentos importantes</h2>
<p><strong>pivot_longer():</strong></p>
<ul>
<li><code>cols</code> - qué columnas pivotar</li>
<li><code>names_to</code> - nombre de nueva variable</li>
<li><code>values_to</code> - nombre de valores</li>
<li><code>values_drop_na</code> - eliminar NAs</li>
<li><code>names_sep</code> / <code>names_pattern</code> - dividir nombres</li>
<li><code>names_prefix</code> - remover prefijo</li>
</ul>
<p><strong>pivot_wider():</strong></p>
<ul>
<li><code>names_from</code> - columna con nombres</li>
<li><code>values_from</code> - columna con valores</li>
<li><code>id_cols</code> - columnas que identifican filas</li>
<li><code>names_prefix</code> - agregar prefijo</li>
<li><code>values_fill</code> - valor para celdas faltantes</li>
</ul>
</section>
<section id="workflow-típico" class="slide level2">
<h2>Workflow típico</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a></a><span class="co"># 1. Leer datos</span></span>
<span id="cb75-2"><a></a>datos <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datos.csv"</span>)</span>
<span id="cb75-3"><a></a></span>
<span id="cb75-4"><a></a><span class="co"># 2. Explorar estructura</span></span>
<span id="cb75-5"><a></a><span class="fu">glimpse</span>(datos)</span>
<span id="cb75-6"><a></a></span>
<span id="cb75-7"><a></a><span class="co"># 3. Identificar problema</span></span>
<span id="cb75-8"><a></a><span class="co">#    - ¿Variables en nombres de columnas? → pivot_longer()</span></span>
<span id="cb75-9"><a></a><span class="co">#    - ¿Observaciones en múltiples filas? → pivot_wider()</span></span>
<span id="cb75-10"><a></a></span>
<span id="cb75-11"><a></a><span class="co"># 4. Pivotar</span></span>
<span id="cb75-12"><a></a>datos_tidy <span class="ot">&lt;-</span> datos <span class="sc">|&gt;</span></span>
<span id="cb75-13"><a></a>  <span class="fu">pivot_longer</span>(...) <span class="co"># o pivot_wider(...)</span></span>
<span id="cb75-14"><a></a></span>
<span id="cb75-15"><a></a><span class="co"># 5. Limpiar tipos y valores</span></span>
<span id="cb75-16"><a></a>datos_clean <span class="ot">&lt;-</span> datos_tidy <span class="sc">|&gt;</span></span>
<span id="cb75-17"><a></a>  <span class="fu">mutate</span>(...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="consejos-finales" class="slide level2">
<h2>Consejos finales</h2>
<ol type="1">
<li class="fragment"><strong>Empieza simple</strong> - usa ejemplos pequeños para entender</li>
<li class="fragment"><strong>Visualiza</strong> - dibuja cómo quieres que se vean los datos</li>
<li class="fragment"><strong>Itera</strong> - prueba, revisa, ajusta</li>
<li class="fragment"><strong>Documenta</strong> - comenta por qué pivoteas de cierta forma</li>
<li class="fragment"><strong>Sé pragmático</strong> - la forma “correcta” es la que facilita tu análisis</li>
<li class="fragment"><strong>No tengas miedo</strong> - des-ordenar y re-ordenar es normal</li>
</ol>
</section>
<section id="errores-comunes" class="slide level2 smaller">
<h2>Errores comunes</h2>
<table class="caption-top">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>Error</th>
<th>Solución</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Olvidas especificar <code>names_to</code> o <code>values_to</code></td>
<td>Ambos son requeridos en <code>pivot_longer()</code></td>
</tr>
<tr class="even">
<td>Múltiples filas por ID en <code>pivot_wider()</code></td>
<td>Especifica <code>id_cols</code> correctamente</td>
</tr>
<tr class="odd">
<td>List-columns inesperadas</td>
<td>Tienes duplicados - usa <code>group_by() + summarize()</code></td>
</tr>
<tr class="even">
<td>NAs no deseados</td>
<td>Usa <code>values_drop_na = TRUE</code></td>
</tr>
<tr class="odd">
<td>Tipos incorrectos después de pivotar</td>
<td>Usa <code>mutate()</code> para corregir tipos</td>
</tr>
</tbody>
</table>
</section>
<section id="recursos-adicionales" class="slide level2">
<h2>Recursos adicionales</h2>
<ul>
<li><a href="https://r4ds.hadley.nz/data-tidy">R for Data Science - Data Tidying</a></li>
<li><a href="https://tidyr.tidyverse.org/articles/pivot.html">tidyr vignette: Pivoting</a></li>
<li><a href="https://www.jstatsoft.org/article/view/v059i10">Tidy Data paper</a> - Teoría y fundamentos</li>
<li><a href="https://tidyr.tidyverse.org/">tidyr documentation</a></li>
<li><a href="https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf">Data transformation cheatsheet</a></li>
</ul>
</section>
<section id="próximos-pasos" class="slide level2">
<h2>Próximos pasos</h2>
<p>En las siguientes sesiones:</p>
<ul>
<li class="fragment"><strong>Manipulación avanzada</strong> con dplyr</li>
<li class="fragment"><strong>Unir datos</strong> de múltiples fuentes</li>
<li class="fragment"><strong>Trabajo con texto</strong> (stringr)</li>
<li class="fragment"><strong>Fechas y tiempos</strong> (lubridate)</li>
<li class="fragment"><strong>Visualización</strong> (ggplot2)</li>
</ul>
</section></section>
<section>
<section id="gracias" class="title-slide slide level1 center" data-background-color="#2C3E50">
<h1>¡Gracias!</h1>

</section>
<div class="centered">
<p><strong>¿Preguntas?</strong></p>
<p>📧 paul.santos@example.com</p>
<p>🌐 Materiales del curso disponibles en el repositorio</p>
<h3 id="próxima-sesión-dplyr---manipulación-avanzada-de-datos">Próxima sesión: dplyr - Manipulación Avanzada de Datos</h3>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://paulefrensa.rbind.io">Paul Efren Santos Andrade</a> // Introducción a R - Tidyverse</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: true,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/posit-conf-2023\.github\.io\/dataviz-ggplot2\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>